# Generated by Django 2.0.2 on 2018-10-26 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actionable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SOLVED', 'SOLVED'), ('IGNORED', 'IGNORED')], default='NEW', max_length=20)),
            ],
            options={
                'verbose_name': 'Actionable',
                'verbose_name_plural': 'Actionables',
            },
        ),
    ]
