# Generated by Django 2.0.2 on 2018-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionable', '0002_auto_20181026_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionable',
            name='level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='WARNING', max_length=20),
        ),
    ]
